# Site settings
title: Young Mercy Links
description: >
  The official website of Young Mercy Links, a group of young adults who
  work together in the spirit of Mercy to help marginalised people and raise
  awareness of social justice issues.
url: "http://youngmercylinks.github.io"
twitter_username: youngmercylinks
github_username:  youngmercylinks

# Build settings
markdown: kramdown

include: ['_pages']
permalink: '/blog/:year/:month/:title.html'
relative_permalinks: false
excerpt_separator: "<!-- more -->"

exclude: ['CNAME', 'Gemfile*', 'exclude', 'README.md', 'LICENCE.txt']

gems:
  - jekyll-sitemap
